### ISSUE TITLE
maven仓库无法下载到sdk

### ISSUE THREAD

**Issue by xiaocain** [baidu/smartapp-openapi-java#8]
下载失败，没有找到这个依赖

**Comment by xiaocain** [comment]
在项目的pom.xml的dependencies中加入
```
<dependency>
			<groupId>com.baidu.mapp</groupId>
			<artifactId>smartapp-api-sdk</artifactId>
			<version>1.1.0-SNAPSHOT</version>
</dependency>
```
下载不到

**Comment by SeriousMa** [comment]
SNAPSHOT版本 部分中央仓库策略不一样 可能不会同步

https://oss.sonatype.org/content/repositories/snapshots/com/baidu/mapp/smartapp-api-sdk/1.1.0-SNAPSHOT/
